---
title: "Race Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## package

```{r}



library(tidyverse)

library(readxl)



```

## data

````{r}









setwd("~/Projects/F1/Data/ergast")



circuits <- read_csv("circuits.csv")

constures <- read_csv("constructor_results.csv")

construcst <- read_csv("constructor_standings.csv")

constructors <- read_csv("constructors.csv")

dristan <- read_csv("driver_standings.csv")


drivers <- read_csv("drivers.csv")


laptimes <- read_csv("lap_times.csv")


pits <- read_csv("pit_stops.csv")

qual = read_csv("qualifying.csv")

races <- read_csv("races.csv")

results <- read_csv("results.csv")

seasons <- read_csv("seasons.csv")

status <- read_csv("status.csv")



tyreuse <- read_csv("F1 Tyre Usage.csv")



```



### functions



```{r}














```







####







```{r}



  
lapcount <- results %>% group_by(raceId) %>%
                            slice_max(laps) %>%
                              distinct(laps, .keep_all = T) %>%
                                select(raceId, laps)


colnames(lapcount)[2] <- "tlap"

  
all_race <- laptimes %>% left_join(races, by = "raceId") %>%
                                left_join(drivers, by = "driverId") %>%
                        left_join(pits, by = c("raceId", "lap", "driverId")) %>%
                            left_join(lapcount, by = "raceId") %>%
                               mutate(seconds = milliseconds.x / 1000) %>%
                                      group_by(code, raceId) %>%
                                      fill(stop, .direction = "down") %>%
                                      mutate(stint = if_else(is.na(stop),1, 1 + stop)) %>%
                                      mutate(lugdur = lag(duration)) %>%
                                        mutate(stopfl = if_else(!is.na(duration),1 ,
                                                          if_else(!is.na(lugdur), 1, 2))) %>%
                                            left_join(lapcount, by = "raceId") %>%
                                              mutate(fuelcor = (tlap.y-(lap-1))* 0.06)  %>%
                                                mutate(lap5 = seconds - fuelcor) %>%
                                                    left_join(min_lap, by = "raceId")  %>%
                                                  mutate(delta = seconds/minlap-1) %>%
                                                          filter(delta < 0.1)

                                                
 


all_race_ms = all_race %>% group_by(code, stint) %>% 
                                    filter(is.na(lugdur)) %>% 
                                      slice_min(lap5) %>%
                                          select(lap, code, lap5)



colnames(all_race_ms)[4] <- "min_lap1"



all_race2 = all_race %>% left_join(all_race_ms, by = c("lap", "code", "stint")) %>%
                              fill(min_lap1) %>%
                               filter(is.na(lugdur)) %>% 
                                  mutate(perdiff = lap5/min_lap1-1)  %>%
                                    mutate(valfil = seconds - min_lap1) %>%
                                        select(raceId, driverId, lap, position, seconds, year, name, round, code, stint, lap5)
















```
```{r}


tyre_tyep = c("soft", "medium", "hard")

tyre_r = c("c3", "c2", "c1")

race = c("Bahrain Grand Prix", "Bahrain Grand Prix", "Bahrain Grand Prix")


```



```{r}



code = c("LEC", "LEC", "LEC","LEC", "SAI", "SAI", "SAI", "SAI", "HAM", "HAM", "HAM", "HAM", "RUS", "RUS", "RUS", "RUS", "MAG", "MAG", "MAG", "MAG", "BOT","BOT", "BOT", "BOT", "OCO", "OCO", "OCO", "OCO", "TSU", "TSU", "TSU","TSU", "ALO", "ALO", "ALO", "ALO", "ZHO", "ZHO", "ZHO", "ZHO", "MSC", "MSC", "MSC", "STR", "STR", "STR", "STR", "ALB", "ALB", "ALB", "ALB", "RIC", "RIC", "RIC", "RIC", "NOR", "NOR","NOR", "NOR", "LAT", "LAT", "LAT", "LAT", "HUL", "HUL", "HUL", "HUL", "PER", "PER", "PER", "PER", "VER", "VER", "VER", "VER", "GAS", "GAS", "GAS")

tyre = c("c3", "c3", "c2", "c3","c3", "c3", "c2", "c3", "c3", "c1", "c2", "c3", "c3", "c1", "c2", "c3","c3", "c3", "c2", "c3","c3", "c2", "c2", "c3","c3", "c2", "c1", "c3","c3", "c2", "c3", "c3",
         "c3", "c1", "c2", "c3","c3", "c2", "c2", "c3", "c3","c2", "c3", "c3","c3", "c2", "c3" , "c3", "c2", "c2", "c3", "c2", "c3", "c1", "c3", "c2", "c1", "c3", "c3", "c3", "c3", "c2", "c3", "c3",
         "c3", "c2", "c3", "c3", "c2", "c3","c3", "c3", "c3", "c2", "c3", "c3", "c2", "c1"
         )



bah_strat = tibble(code, tyre) %>%
                      group_by(code) %>%
                        mutate(stint = 1:n())




```





````{r}




stint_min = all_race2 %>% group_by(raceId, code, stint) %>%
                              slice_min(lap5) %>%
                                select(raceId, code, stint,lap5)


colnames(stint_min)[4] = "minl"



stint_min2 = all_race2 %>% left_join(stint_min, by = c("raceId", "code", "stint")) %>%
                                      mutate(delta = lap5/minl-1) %>% 
                                        filter(year == 2022) %>%
                                          filter(round == 1) %>%
                                              left_join(bah_strat, by = c("code", "stint")) %>%
                                                  group_by(code, stint) %>%
                                                      mutate(stintl = 1:n()) %>% 
                                                                  filter(stintl > 1)


ggplot(stint_min2, aes(x = stintl, y = delta)) + geom_point() + facet_wrap(~tyre)


```





```{r}


soft_stin_ex = soft_stin %>% filter(stintl < 21) %>% 
                              group_by(stintl) %>% 
                              summarise(avpred = mean(pred)) %>% 
                                  select(stintl, avpred) %>% 
                                      mutate(method = "predicted")


colnames(soft_stin_ex)[2] = "delta" 


soft_comp = stint_min2 %>% filter(tyre == "c3") %>% 
                              select(stintl, delta) %>%
                                  mutate(method = "Actual") %>% 
                                      bind_rows(soft_stin_ex)



ggplot(soft_comp, aes(x = stintl, y= delta, col = method)) + geom_point()














```





```{r}



fast_lap = stint_min2 %>% group_by(lap) %>% 
                              slice_min(lap5) %>% 
                                select(lap, lap5)


colnames(fast_lap)[2] = "flap"


fast_lap2 = stint_min2 %>% left_join(fast_lap, by = "lap") %>% 
                                mutate(perdiff = lap5/flap -1 ) %>% 
                                    group_by(code) %>% 
                                      summarise(perdiffm = median(perdiff))



ggplot(fast_lap2, aes(x = reorder(code,perdiffm), y = perdiffm)) + geom_col() + coord_flip()



```




```{r}




teams = c("Red Bull","Red Bull", "Mercedes", "Mercedes", "Ferrari", "Ferrari", "Mclaren", "Mclaren", "Alpine",  "Alpine",  "Alpha Tauri", "Alpha Tauri", "Aston Martin", "Aston Martin","Aston Martin" , "Williams",  "WIlliams", "Alfa Romea",  "Alfa Romeo",  "Haas","Haas")


code = c("PER", "VER", "HAM" , "RUS", "SAI" , "LEC" , "NOR" , "RIC" ,  "ALO", "OCO" , "GAS", "TSU", "STR", "HUL" ,"VET","ALB" , "LAT",  "BOT", "ZHO" , "MAG", "MSC")


teamdri = tibble(teams, code)



fast_lap_all = all_race2 %>%  filter(year == 2022)  %>% 
                                group_by(raceId, lap) %>% 
                                    slice_min(lap5) %>% 
                                      select(raceId, lap, lap5)


colnames(fast_lap_all)[3] = "flap"


fast_lap_all2 = all_race2 %>% filter(year == 2022)  %>% 
                                      left_join(fast_lap_all, by = c("raceId", "lap")) %>% 
                                        mutate(perdiff = lap5/flap -1 ) %>% 
                                          left_join(teamdri, by = "code") %>% 
                                              group_by(raceId, teams, lap) %>% 
                                                slice_min(perdiff) %>% 
                                                    ungroup() %>% 
                                                        group_by(round, teams) %>% 
                                                            summarise(perdiffm = median(perdiff))
  






ggplot(fast_lap_all2, aes(x = round, y = perdiffm, col = teams)) + geom_point()









```



